version: '3.4'

services:
  CatalogDb:
    container_name: CatalogDb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogdbSettings:ConnectionString=mongodb://CatalogDb:27017"
    ports:
      - "8001:80"
    depends_on:
      - CatalogDb

  RedisDb:
    container_name: RedisDb
    restart: always
    ports:
      - 6379:6379

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString:Redis=RedisDb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
    depends_on:
      - RedisDb
    ports:
      - "8002:80"

  DiscountDb:
    container_name: DiscountDb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin12345
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  Pgadmin:
    container_name: Pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: 
      always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin


  discount.api:
    container_name: discount.api    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=Server=DiscountDb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin12345
    depends_on:
      - DiscountDb
    ports:
      - "8003:80"


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=Server=DiscountDb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin12345
    depends_on:
      - DiscountDb
    ports:
      - "8004:80"